use anchor_lang::prelude::*; //import-ish statement

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"); // id w/ program run info for Solana. Temp autogenerated.

#[program] // program declaration macro
pub mod octproject {
    use super::*;
    pub fn start_stuff_off(ctx: Context<StartStuffOff>) -> ProgramResult {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct StartStuffOff {}
